apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clients-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile  # StorageClass that allows ReadWriteMany
  resources:
    requests:
      storage: 2Gi